# Use root/example as user/password credentials
version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:  
      - 5050:5050
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: "mongodb://root:example@assignment4-mongo-1:27017/"
  webapi:
    build: .
    restart: always
    ports:
      - 5001:80
      - 5000:443
    environment:
      MongoDB__Host: mongo
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTPS_PORT: 5001
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    depends_on:
    - mongo
    volumes:
      - ~/.aspnet/https:/https:ro
